autoInstallPeers: false

dedupePeerDependents: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true
