autoInstallPeers: true

dedupePeerDependents: true

allowBuilds:
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false

overrides:
  fast-uri: ^3.1.3
