autoInstallPeers: false

dedupePeerDependents: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver

overrides:
  jiti: <2.2.0

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true
